### ISSUE TITLE
Key not found in the index.

### ISSUE THREAD

**Issue by talon** [modella/leveldb#3]
I'm working on a login system with users and have Modella model like so:

``` javascript
var User = model('User')
   .attr('id')
   .attr('email')

User.use(level)
User.index('email', {unique: true})
```

And when I try to do this:

``` javascript
User.find({email: 'user@example.com'}, function(err, user) {
  console.log(user) // never gets called.
})
```

I get this error:

```
Error: Key not found in the index.
    at error (node_modules/modella-leveldb/node_modules/leveldex/index.js:227:13)
    at node_modules/modella-leveldb/node_modules/leveldex/index.js:143:55
    at dispatchError (node_modules/modella-leveldb/node_modules/level-11/node_modules/level-packager/node_modules/levelup/lib/util.js:131:7)
    at node_modules/modella-leveldb/node_modules/level-11/node_modules/level-packager/node_modules/levelup/lib/levelup.js:197:14
```

I'm not sure if this is my own mistake or something with `leveldex` or `modella-leveldb`

**Comment by talon** [comment]
-_- Rookie mistake. That error means that the item isn't in the database.
